use File::Path qw(make_path);

$pdf_mode  = 4;
$aux_dir   = '.build';
$out_dir   = '.';
$clean_ext = 'out xsim';

$lualatex = 'lualatex %O -halt-on-error -synctex=1 --shell-escape %S';

my %flags = (
    '--print'     => q{\newcommand{\printmodebool}{true}},
    '--solutions' => q{\newcommand{\printsolutionbool}{true}},
);

my @pretex;

@ARGV = grep {
    if (exists $flags{$_}) {
        push @pretex, $flags{$_};
        0;
    }
    else {
        1;
    }
} @ARGV;

my $practice_flags_file = "$aux_dir/practice-latexmk-flags.state";
my $pretex = join('', @pretex);
my $old_pretex = '';
my $pretex_changed = 0;

make_path($aux_dir) unless -d $aux_dir;

if (open my $fh, '<', $practice_flags_file) {
    local $/;
    $old_pretex = <$fh>;
    close $fh;
}

if ($old_pretex ne $pretex) {
    open my $fh, '>', $practice_flags_file
        or die "Cannot write $practice_flags_file: $!";
    print {$fh} $pretex;
    close $fh;
    $pretex_changed = 1;
}

# Flagged builds share normal output names, so force them. The state file forces
# the first normal build after a flagged build.
splice @ARGV, 0, 0, '-g' if @pretex || $pretex_changed;

splice @ARGV, 0, 0,
    '-shell-escape',
    '-usepretex=' . $pretex
    if @pretex;

ensure_path('LUAINPUTS', '..//');
ensure_path('LUAINPUTS', '../.dependencies//');
ensure_path('TEXINPUTS', '..//');
ensure_path('TEXINPUTS', '../.dependencies//');

# Quiz print mode uses the same quiz example with \printmodebool enabled:
# latexmk --print example.quiz.tex
