$pdf_mode  = 4;
$aux_dir   = '.build';
$out_dir   = '.';
$clean_ext = 'out xsim';

$lualatex = 'lualatex %O -halt-on-error --shell-escape %S';

ensure_path('TEXINPUTS', '../.dependicies//');
ensure_path('TEXINPUTS', '..//');
ensure_path('LUAINPUTS', '..//');

# Quiz print mode uses the same quiz example with \print defined:
# latexmk -lualatex='lualatex %O -halt-on-error --shell-escape "\def\print{}\input{%S}"' example.quiz.tex
